# Generated by Django 5.0.4 on 2024-05-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundme',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
