# Generated by Django 5.0.4 on 2024-05-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_company_rename_transaction_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundme',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
