# Generated by Django 5.0.4 on 2024-06-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_alter_bankaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundme',
            name='status',
            field=models.CharField(choices=[('settled', 'settled'), ('funding', 'funding')], default='funding', max_length=20),
        ),
    ]
