# Generated by Django 5.0.7 on 2024-07-25 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_fundme_fund_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundme',
            name='image',
        ),
    ]
