# Generated by Django 5.0.4 on 2024-05-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_organization_sponsorship_delete_partnership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='image',
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
