# Generated by Django 5.0.4 on 2024-05-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_fundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundimage',
            name='sub_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
