# Generated by Django 5.0.4 on 2024-04-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_volunteer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('Voluntesr', 'Volunteer'), ('Donner', 'Donner')], max_length=50),
        ),
    ]
