# Generated by Django 5.0.7 on 2024-07-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_remove_fundme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='about_organ',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, choices=[('Government', 'Government'), ('Private', 'Private'), ('None-Profit', 'None-Profit'), ('Personal', 'Personal'), ('Emergency', 'Emergency'), ('National Funding', 'National Funding')], max_length=100, null=True),
        ),
    ]
