# Generated by Django 5.0.4 on 2024-05-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_alter_fundme_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='fundme',
        ),
    ]
