# Generated by Django 5.0.4 on 2024-05-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_remove_organization_user_remove_sponsorship_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
