# Generated by Django 5.0.4 on 2024-06-03 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_alter_bankaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundme',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.organization'),
        ),
    ]
