# Generated by Django 5.0.4 on 2024-05-28 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_remove_organization_fundme'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('fundme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fundme')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
