# Generated by Django 5.0.7 on 2024-07-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_organization_about_organ_alter_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organ_website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
