# Generated by Django 5.0.4 on 2024-05-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_alter_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
