# Generated by Django 5.0.4 on 2024-05-11 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_imagecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.imagecategory'),
        ),
    ]
