# Generated by Django 5.0.4 on 2024-06-01 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_organfund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreaction',
            name='profile',
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='fundme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.fundme'),
        ),
    ]
