# Generated by Django 5.0.4 on 2024-05-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_organization_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundme',
            old_name='earned',
            new_name='target',
        ),
    ]
