# Generated by Django 5.0.4 on 2024-06-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_fundme_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundme',
            name='organization',
        ),
    ]
