# Generated by Django 5.0.4 on 2024-06-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0006_remove_commentreaction_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='wallet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='status',
            field=models.CharField(choices=[('Philantropist', 'Philantropist'), ('Donner', 'Donner'), ('organization', 'organization')], max_length=50),
        ),
    ]
