# Generated by Django 5.0.4 on 2024-05-20 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0006_rename_earned_fundme_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.category'),
        ),
    ]
