# Generated by Django 5.0.7 on 2024-07-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, choices=[('Government', 'Government'), ('Private', 'Private'), ('None-Profit', 'None-Profit'), ('Personal', 'Personal')], max_length=100, null=True),
        ),
    ]
