# Generated by Django 5.0.4 on 2024-05-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0007_commentreaction_event_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreaction',
            name='react',
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='emaji',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
