# Generated by Django 5.0.7 on 2024-07-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0007_remove_bankaccount_user_bankaccount_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundme',
            name='organizer_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
