# Generated by Django 5.0.7 on 2024-07-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0008_category_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='wallet',
            new_name='balance',
        ),
    ]
