# Generated by Django 5.0.7 on 2024-07-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0008_fundme_organizer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField()),
                ('web_site', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
