# Generated by Django 5.0.4 on 2024-05-12 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0008_remove_commentreaction_react_commentreaction_emaji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donor',
            new_name='donor_fullname',
        ),
        migrations.AlterField(
            model_name='donation',
            name='fundme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.fundme'),
        ),
    ]
