# Generated by Django 5.0.7 on 2024-07-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0009_rename_wallet_organization_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundme',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
