# Generated by Django 5.0.7 on 2024-07-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0009_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='web_site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
