# Generated by Django 5.0.4 on 2024-05-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0009_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
