# Generated by Django 5.0.7 on 2024-07-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0010_fundme_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
