# Generated by Django 5.0.7 on 2024-07-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0011_alter_organization_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('name_or_time', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slogan', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
