# Generated by Django 5.0.7 on 2024-07-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0012_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
