# Generated by Django 5.0.7 on 2024-07-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0013_donation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
