# Generated by Django 5.0.7 on 2024-07-24 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0014_transactions_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='type',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='name',
        ),
        migrations.AddField(
            model_name='transactions',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.organization'),
        ),
    ]
