# Generated by Django 5.0.7 on 2024-07-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0015_rename_type_transactions_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundme',
            name='organizer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
