# Generated by Django 5.0.7 on 2024-07-25 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('fund', '0005_organization_organ_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.organization'),
        ),
    ]
