# Generated by Django 5.0.4 on 2024-05-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loggedinuserdevices_userverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=100, max_length=30, null=True),
        ),
    ]
