# Generated by Django 5.0.4 on 2024-05-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_phone_user_phone_number'),
        ('fund', '0003_remove_organization_user_remove_sponsorship_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orgaization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.organization'),
        ),
    ]
