# Generated by Django 5.0.4 on 2024-05-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_orgaization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='orgaization',
            new_name='organization',
        ),
    ]
