# Generated by Django 5.0.4 on 2024-05-13 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_orgaization_user_organization'),
        ('fund', '0005_organization_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sponsorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.sponsorship'),
        ),
    ]
