# Generated by Django 5.0.4 on 2024-05-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_sponsorship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_status',
            new_name='status',
        ),
    ]
