# Generated by Django 5.0.4 on 2024-05-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_user_status_user_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStatus',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='gender',
        ),
    ]
